//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LambdaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssignments //εδω
    {
        public int StudentsAssignmentsID { get; set; }
        public int StudentCoursesID { get; set; }
        public int AssignmentCourseID { get; set; }
    
        public virtual AssignmentsCourse AssignmentsCourse { get; set; }
        public virtual StudentCourses StudentCourses { get; set; }
    }
}
